doctrine:
    dbal:
        driver: pdo_sqlite
        path: "%kernel.root_dir%/../var/app.sqlite"
        charset:  UTF8
    orm:
        auto_generate_proxy_classes: false
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            app:
                type: annotation
                dir: "%kernel.root_dir%/Entity"
                prefix: "Psi\\Bundle\\Admin\\Example\\app\\Entity"
