imports:
    - { resource: "cmf/_main.yml" }

framework:
    secret: secret
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:
        enabled: true
    templating:
        enabled: true
        engines:
            - twig

